name: Tests

on:
  push:
  pull_request:
  schedule:
    # Weekly run to detect changes in future Python / dependencies
    - cron: "0 3 * * 1"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # ------------------------
          # Supported Python versions
          # ------------------------
          - python-version: "3.11"
            allow-failure: false
          - python-version: "3.12"
            allow-failure: false
          - python-version: "3.13"
            allow-failure: false
          - python-version: "3.14"
            allow-failure: false
          # ------------------------
          # Future versions
          # ------------------------
          - python-version: "3.15"
            allow-failure: true

    continue-on-error: ${{ matrix.allow-failure }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install tox
        run: pip install tox

      - name: Run tox
        run: tox
